title: 'Revise & Resub'
default_lang: en
author:
  name: 'Nick Hayward'
  email: nhayward2011@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'In this contest, authors will be eligible to receive feedback and full edits on their manuscript from professional editors, ensuring their works are polished and ready for those agent inboxes.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /editors/carly-bornstein-hayward: '/editors/carly-hayward[301]'
  /editors/hannah-vanvels$: '/editors/hannah-vanvels-ausbury[301]'
routes: null
blog:
  route: /blog
